version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - MONGO_URI=${MONGO_URI_DOCKER}
      - ENVIRONMENT=dev
      - IP=0.0.0.0
      - PORT=3000
      - JWT_SECRET=localSecret
      - RUN_PROCEDURES=true
      - RUN_ROUTINES=true
    depends_on:
      - postgres
      - mongo
      - mailhog
    volumes:
      - .:/app
    networks:
      - default

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_do_postgres
      POSTGRES_DB: filmes
    ports:
      - "5432:5432"
    networks:
      - default

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - default

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - default

networks:
  default:
    driver: bridge
